version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: '/packages/design-tokens'
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: '/packages/headless-styles'
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: '/packages/icons'
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: '/packages/react'
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: '/packages/react-utils'
    schedule:
      interval: daily
