name: ðŸ“– Documentation

on:
  push:
    paths:
      - 'website/**'
    branches:
      - main

jobs:
  gh-release:
    runs-on: ubuntu-latest
    name: ðŸš€ Release to GitHub Pages
    env:
      USE_SSH: true
      GIT_USER: ${{ secrets.GH_USERNAME }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.4.0'
          cache: 'yarn'
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USER }}
          yarn install
          yarn deploy:website
