on: [push]

jobs:
  lint-css:
    runs-on: ubuntu-latest
    name: ğŸ’… Check for CSS errors
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint:css

  lint-js:
    runs-on: ubuntu-latest
    name: ğŸ’… Check for JS errors
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint:js

  # TODO: Uncomment when starting to use TS
  # lint-ts:
  #   runs-on: ubuntu-latest
  #   name: ğŸ’… Check for TS errors
  #   steps:
  #     - uses: actions/checkout@v2.4.0
  #     - uses: actions/setup-node@v3
  #     - run: yarn install
  #     - run: yarn lint:ts
