name: ðŸ’… Lint Checks

on: [merge_group, pull_request]

jobs:
  lint-css:
    runs-on: ubuntu-latest
    name: CSS valid
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace @pluralsight/design-tokens run lint:css
      - run: yarn workspace @pluralsight/headless-styles run lint:css

  lint-js:
    runs-on: ubuntu-latest
    name: JS valid
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint:js

  lint-ts:
    runs-on: ubuntu-latest
    name: TS valid
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint:ts
