on:
  push:
    branches:
      - main

jobs:
  build-packages:
    runs-on: ubuntu-latest
    name: ğŸ‘·â€â™€ï¸ Build all packages
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: |
          yarn install
          yarn build:packages
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: packages/**/build

  experimental-release:
    runs-on: ubuntu-latest
    name: ğŸš€ Publish experimental release
    needs: build-packages
    env:
      RELEASE_CHANNEL: 'experimental'
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: |
          yarn config set -H 'npmAuthToken' "${{ secrets.NPM_TOKEN }}"
          yarn update:deps
          yarn install
          yarn prepare:release --release experimental --commit=$GITHUB_SHA --ci
          yarn publish:packages --ci --tags experimental
