# on:
#   push:
#     branches:
#       - main
on:
  pull_request:
    branches:
      - main

jobs:
  build-packages:
    runs-on: ubuntu-latest
    name: ğŸ‘·â€â™€ï¸ Build all packages
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: |
          yarn install
          yarn build:packages
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: packages/**/build

  experimental-release:
    runs-on: ubuntu-latest
    name: ğŸš€ Publish experimental release
    needs: build-packages
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: |
          npm config set @pluralsight:registry https://repository.vnerd.com/artifactory/api/npm/npm-pluralsight/
          yarn install
          yarn prepare:release --release experimental --commit=$GITHUB_SHA --ci
          yarn publish:packages --ci --tags experimental

  next-release:
    runs-on: ubuntu-latest
    name: ğŸš€ Publish next release
    needs: build-packages
    env:
      USE_SSH: true
      GIT_USER: ${{ secrets.GH_USERNAME }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: |
          npm config set @pluralsight:registry https://repository.vnerd.com/artifactory/api/npm/npm-pluralsight/
          yarn install
          yarn prepare:release --release next --commit=$GITHUB_SHA --ci
          yarn publish:packages --ci --tags alpha,next
