on:
  push:
    branches:
      - main

env:
  RELEASE_CHANNEL: 'next'

jobs:
  build-packages:
    runs-on: ubuntu-latest
    name: ğŸ‘·â€â™€ï¸ Build next packages
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: |
          yarn install
          yarn prepare:flags
          yarn build:packages
          tar -cvf packages_next.tar packages
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: next_packages
          path: packages_next.tar

  next-release:
    runs-on: ubuntu-latest
    name: ğŸš€ Publish next release
    needs: build-packages
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - uses: actions/download-artifact@v3
        with:
          name: next_packages
      - run: |
          yarn config set -H 'npmAuthToken' "${{ secrets.NPM_TOKEN }}"
          yarn prepare:release --release next --commit=$GITHUB_SHA --ci
          yarn publish:packages --ci --tags next
