on:
  push:
    branches:
      - main

env:
  RELEASE_CHANNEL: 'experimental'

jobs:
  build-packages:
    runs-on: ubuntu-latest
    name: ğŸ‘·â€â™€ï¸ Build experimental packages
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: |
          yarn install
          yarn prepare:flags
          yarn build:packages
          tar -cvf experimental_packages.tar packages
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: experimental_packages
          path: experimental_packages.tar

  experimental-release:
    runs-on: ubuntu-latest
    name: ğŸš€ Publish experimental release
    needs: build-packages
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: experimental_packages
      - run: |
          tar -xf ./experimental_packages.tar
          yarn config set -H 'npmAuthToken' "${{ secrets.NPM_TOKEN }}"
          yarn prepare:release --release experimental --commit=$GITHUB_SHA --ci
          yarn publish:packages --ci --tags experimental
